# Generated by Django 3.2.4 on 2021-06-15 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='captions',
            new_name='caption',
        ),
    ]
